Homework #4 for checking
Anvar-Kartakaev/homework4 pull request #1
Opened 2024-09-16 13:20 UTC by Anvar-Kartakaev

2024-09-16 19:30 UTC, isavinov requested changes

2024-09-16 19:30 UTC, isavinov commented on src/Main.java
> +        if (childAge3 > 14 && childAge3 > 5) {
Нужно еще подумать над условием
&& - логическое и. Истинно, когда и правая и левая часть истины
А тут получается, что
если возраст > 14 , то это значение > 5 по определению
если значение < 14, то несмотря на правую часть оно будет ложным

Вся правая часть выражения не играет в условии никакой роли

2024-09-16 19:30 UTC, isavinov commented on src/Main.java
> +        if (childAge1 > 5 && childAge1 < 14) {
Нужно доработать, возраст надо проверить по 3м критериям. По аналогии с 4й задачей

2024-09-16 19:30 UTC, isavinov commented on src/Main.java
> +        if (trainSeats <= 120 && trainSeats > 0 && seatingPlaces <= 60 && seatingPlaces > 0 && standingPlaces <= (trainSeats - seatingPlaces) && standingPlaces > 0) {
Очень сложное для восприятия условие - нужно упрощать. По сути делается по аналогии с предыдущими
Есть переменная - количество людей, это переменная сравнивается с 60 и со 102, чтобы определить есть ли и какие места в вагоне

2024-09-17 09:10 UTC, Anvar-Kartakaev commented on src/Main.java
> +        if (childAge3 > 14 && childAge3 > 5) {
Решил полностью изменить подход с помощью boolean

2024-09-17 09:10 UTC, Anvar-Kartakaev commented on src/Main.java
> +        if (childAge1 > 5 && childAge1 < 14) {
Решил полностью изменить подход с помощью boolean

2024-09-17 09:27 UTC, Anvar-Kartakaev commented on src/Main.java
> +        if (trainSeats <= 120 && trainSeats > 0 && seatingPlaces <= 60 && seatingPlaces > 0 && standingPlaces <= (trainSeats - seatingPlaces) && standingPlaces > 0) {
Скорректировал, плюс изменил подход с помощью boolean

2024-09-17 09:52 UTC, Anvar-Kartakaev commented on src/Main.java
> +        boolean freeSeatsOne = (trainSeats + (seatingPlaces + standingPlaces) != 0);
Здесь я упустил ошибку, удалю лишнее и будет выглядеть так: boolean freeSeatsOne = seatingPlaces + standingPlaces != 0

2024-09-17 09:53 UTC, Anvar-Kartakaev commented on src/Main.java
> +        boolean freeSeatsTwo = (trainSeats + (seatingPlaces + standingPlaces)) != 0;
Здесь я тоже упустил ошибку, удалю лишнее и будет выглядеть так: boolean freeSeatsTwo = seatingPlaces + standingPlaces != 0;

2024-09-17 16:42 UTC, merged